AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: general-deploy
        S3Key: deploy-package.zip
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs14.x
      Timeout: 10
    DependsOn:
      - LambdaExecutionRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9dc93ca0-621f-44e1-8dc6-e04482b12685
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7108ae17-0ca7-407e-9d08-84f372534826
  ApiGatewayHttpApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: MyHttpApi
      ProtocolType: HTTP
      Description: An HTTP API for my Lambda function
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
        AllowMethods:
          - GET
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b1071f96-a1df-4bbf-bf72-c86cfa922a91
  ApiGatewayHttpApiIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref ApiGatewayHttpApi
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: '2.0'
      IntegrationUri: !Sub >-
        arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
    DependsOn:
      - ApiGatewayHttpApi
      - LambdaFunction
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ded1e389-aab8-43a0-9481-aec4993160a7
  ApiGatewayHttpApiRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref ApiGatewayHttpApi
      RouteKey: GET /hello
      Target: !Join
        - /
        - - integrations
          - !Ref ApiGatewayHttpApiIntegration
    DependsOn:
      - ApiGatewayHttpApiIntegration
      - ApiGatewayHttpApi
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 79dc1096-966f-4434-97a7-37419a02cae1
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub '${ApiGatewayHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
            Id: apigateway
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: apigateway
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:848023796141:certificate/6aeba91c-0828-444e-b09d-ce5e5326c46b
          SslSupportMethod: sni-only
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: apigateway
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            MinTTL: 300
    DependsOn:
      - ApiGatewayHttpApi
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 64266757-f587-44d7-a043-0656e3ea34d5
Metadata:
  'AWS::CloudFormation::Designer':
    b1071f96-a1df-4bbf-bf72-c86cfa922a91:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    64266757-f587-44d7-a043-0656e3ea34d5:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': -10
      z: 1
      embeds: []
      dependson:
        - b1071f96-a1df-4bbf-bf72-c86cfa922a91
    7108ae17-0ca7-407e-9d08-84f372534826:
      size:
        width: 60
        height: 60
      position:
        x: 350
        'y': 210
      z: 1
      embeds: []
    9dc93ca0-621f-44e1-8dc6-e04482b12685:
      size:
        width: 60
        height: 60
      position:
        x: 240
        'y': 210
      z: 1
      embeds: []
    ded1e389-aab8-43a0-9481-aec4993160a7:
      size:
        width: 60
        height: 60
      position:
        x: 120
        'y': 210
      z: 1
      embeds: []
      dependson:
        - 9dc93ca0-621f-44e1-8dc6-e04482b12685
    79dc1096-966f-4434-97a7-37419a02cae1:
      size:
        width: 60
        height: 60
      position:
        x: 10
        'y': 210
      z: 1
      embeds: []
    7d5d939e-c11c-4ec9-a80c-a5a9ac7d7951:
      source:
        id: ded1e389-aab8-43a0-9481-aec4993160a7
        selector: 'g:nth-child(1) g:nth-child(4) g:nth-child(1) circle:nth-child(1)     '
        port: 'AWS::DependencyLink-*'
      target:
        id: 9dc93ca0-621f-44e1-8dc6-e04482b12685
      z: 12
