# This Cloud Formation template is used for runtime infrastructure
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DeployBucketName:
    Type: String
    Description: The deploy bucket name.
Resources:
  WebResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: code-and-coffee-service-web-resources
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref DeployBucketName
        S3Key: lambda-package.zip
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::848023796141:role/code-and-coffee-service-lambda-role
      Runtime: nodejs14.x
      Timeout: 10
  ApiGatewayHttpApi:
    Type: "AWS::ApiGatewayV2::Api"
    Properties:
      Name: MyHttpApi
      ProtocolType: HTTP
      Description: An HTTP API for my Lambda function
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
  ApiGatewayHttpApiIntegration:
    Type: "AWS::ApiGatewayV2::Integration"
    Properties:
      ApiId: !Ref ApiGatewayHttpApi
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
    DependsOn:
      - ApiGatewayHttpApi
      - LambdaFunction
  ApiGatewayHttpApiRoute:
    Type: "AWS::ApiGatewayV2::Route"
    Properties:
      ApiId: !Ref ApiGatewayHttpApi
      RouteKey: GET /hello
      Target: !Join
        - /
        - - integrations
          - !Ref ApiGatewayHttpApiIntegration
    DependsOn:
      - ApiGatewayHttpApiIntegration
      - ApiGatewayHttpApi
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${ApiGatewayHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
            Id: apigateway
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: apigateway
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:848023796141:certificate/6aeba91c-0828-444e-b09d-ce5e5326c46b
          SslSupportMethod: sni-only
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: apigateway
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            MinTTL: 300
    DependsOn:
      - ApiGatewayHttpApi
