# Nested CloudFormation stack to allow us to tag all the resources properly.
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DeployBucketName:
    Type: String
    Description: The deploy bucket name.
  LambdaKey:
    Type: String
    Description: The key of the lambda package in the deploy bucket.
Resources:
  CodeAndCoffeeServiceNested:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${DeployBucketName}/deploy.template.yaml
      Parameters:
        DeployBucketName: !Ref DeployBucketName
        LambdaKey: !Ref LambdaKey
      Tags:
        - Key: app
          Value: code-and-coffee-service
