name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: time
        with:
          format: LLLL
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "##"
          tokenSuffix: "##"
          files: '["**/*.js","**/**/*.js","**/*.json","**/**/*.json","**/*.ts","**/**/*.ts"]'
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          BUILD_DATE: ${{ steps.time.outputs.formattedTime }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ github.sha }}.zip lambda-package
      - name: Create Deploy Bucket
        run: aws s3 mb s3://${{ secrets.S3_DEPLOY_BUCKET_NAME }}
      - name: Upload lambda package to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://${{ secrets.S3_DEPLOY_BUCKET_NAME }}/${{ github.sha }}.zip
      - name: Upload deploy.template.yaml to S3
        run: aws s3 cp deploy.template.yaml s3://${{ secrets.S3_DEPLOY_BUCKET_NAME }}/deploy.template.yaml
      - name: Execute CloudFormation template
        run: aws cloudformation deploy --template-file master-deploy.template.yaml --stack-name code-and-coffee-service --parameter-overrides DeployBucketName=${{ secrets.S3_DEPLOY_BUCKET_NAME }} LambdaKey=${{ github.sha }}.zip AcmCertificateArn=${{ secrets.ACM_CERTIFICATE_ARN }}
      - name: Upload dist to web resources bucket
        run: aws s3 sync dist s3://code-and-coffee-service-web-resources
      - name: Publish SNS topic success
        if: ${{ success() }}
        uses: nothingalike/sns-publish-topic@v1.6
        with:
          MESSAGE: "${{ github.repository }} '${{ github.workflow }}.${{ github.run_number }}' successful"
          TOPIC_ARN: ${{ secrets.SNS_ARN }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Publish SNS topic failure
        if: ${{ !success() }}
        uses: nothingalike/sns-publish-topic@v1.6
        with:
          MESSAGE: "${{ github.repository }} '${{ github.workflow }}.${{ github.run_number }}' failure"
          TOPIC_ARN: ${{ secrets.SNS_ARN }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
